name: build

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          ref: 'master'

      - name: Install dependencies
        run: |
          sudo apt-get -q update
          sudo apt-get install -y nodejs npm dos2unix gettext
          npm install -g jshint
          pip3 install Cheetah3 six autopep8 flake8 bandit

      - uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Build python 3.9
        run: |
          pip3 install Cheetah3
          pip3 install six
          python -m compileall -l . -r 10 -q
          cheetah compile -R plugin
          python testsuite/evil_eval.py
          ./CI/build.sh
          ./CI/create_ipk.sh
          ./CI/create_ipk.sh vti
          ./CI/create_ipk.sh deb
          bandit -r plugin -f html -o bandit.html || true
          python -m flake8 --ignore=W191,E501,E302,E711,E128,E265 --extend-exclude plugin/controllers/views/ plugin/ --output-file flake8_report.txt || true
          jshint ./sourcefiles/js/ | tee jshint1_report.txt
          jshint ./sourcefiles/modern/js/ | tee jshint2_report.txt

      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./Rel
          force_orphan: true
